NUM_TRADERS = 1000
PERC_RISKY_TRADERS = 0.2
PERC_MODERATE_TRADERS = 0.3
PERC_SAFE_TRADERS = 1 - PERC_MODERATE_TRADERS - PERC_RISKY_TRADERS

PERCENT_BOUND_HIGH = 0.3
PERCENT_BOUND_MID = 0.2
PERCENT_BOUND_LOW = 1 - PERCENT_BOUND_HIGH - PERCENT_BOUND_MID
MONTE_CARLO_SIMULATIONS = 1

ETH_AMOUNT_TRADER = 2
NOI_AMOUNT_TRADER = 1000

ETH_AMOUNT_POOL = 200
NOI_AMOUNT_POOL = 100000