NUM_TRADERS = 500
PERC_RISKY_TRADERS = 0.2
PERC_MODERATE_TRADERS = 0.3
PERC_SAFE_TRADERS = 1 - PERC_MODERATE_TRADERS - PERC_RISKY_TRADERS

PERCENT_BOUND_HIGH = 0.3
PERCENT_BOUND_MID = 0.2
PERCENT_BOUND_LOW = 1 - PERCENT_BOUND_HIGH - PERCENT_BOUND_MID
MONTE_CARLO_SIMULATIONS = 1

NUM_LEVERAGERS = 100
PERC_RISKY_LEVERAGER = 0.2
PERC_MODERATE_LEVERAGER = 0.3
PERC_SAFE_LEVERAGER = 1 - PERC_MODERATE_LEVERAGER - PERC_RISKY_LEVERAGER

# relative difference between initial cr and repay/boost cr of leverager
R_LEV_DIFF = 0.1
M_LEV_DIFF = 0.25
S_LEV_DIFF = 0.5

#initial cr of leverager
R_LEV_CR = 1.5
M_LEV_CR = 1.9
S_LEV_CR = 2.5

#percent of leveragers(risky leveragers put more percent of their money in collateral)
PERCENT_R_LEV_COLLATERAL = 1
PERCENT_M_LEV_COLLATERAL = 0.7
PERCENT_S_LEV_COLLATERAL = 0.5


ETH_AMOUNT_TRADER = 20
NOI_AMOUNT_TRADER = 10000

ETH_AMOUNT_POOL = 2000
NOI_AMOUNT_POOL = 1000000

INITIAL_CR = 1.5

LIQUIDATION_RATIO = 1.2