
parameters = [
    {},
#     {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 0,
#     'instant_price': 0,
#     'instant_rate': 0,
#     'longterm_price': 0
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 50,
#     'instant_rate': 50,
#     'longterm_price': 0
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 100,
#     'instant_rate': 100,
#     'longterm_price': 0
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 0,
#     'instant_rate': 0,
#     'longterm_price': 20
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 0,
#     'instant_rate': 0,
#     'longterm_price': 80
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 0,
#     'instant_rate': 0,
#     'longterm_price': 200
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 30,
#     'instant_rate': 30,
#     'longterm_price': 30
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 60,
#     'instant_rate': 60,
#     'longterm_price': 60
# },
# {
#     'rate_trader': 10,
#     'price_trader': 10,
#     'leverager': 100,
#     'safe_owner': 100,
#     'whale_instant_price_setter': 1,
#     'whale_instant_rate_setter': 1,
#     'whale_longterm_price_setter': 1,
#     'instant_price': 100,
#     'instant_rate': 100,
#     'longterm_price': 100
# },
]